model_version: CogVideoX-2B
ckpt_path: "models/CogVideoX-2b/transformer/diffusion_pytorch_model.safetensors"

t5_model: transformers
t5_model_dir: "models/t5-v1_1-xxl/"
t5_dtype: fp16

vae_type: "CogVideoX-VAE"
vae_checkpoint: "models/CogVideoX-2b/vae/diffusion_pytorch_model.safetensors"
vae_dtype: fp16
sd_scale_factor: 1.15258426

image_size: [ 480, 720 ]
num_frames: 49
enable_flash_attention: True
model_max_length: 226
dtype: fp16
batch_size: 1

# sampling
sampling_steps: 50
guidance_scale: 6.0
seed: 42
sampling: ddim
noise_schedule: quad
v_pred: True
beta_start: 0.00085
beta_end: 0.012
snr_shift_scale: 3.0
rescale_betas_zero_snr: True

# ms
mode: 1
jit_level: O0

# other
save_format: gif

captions:
  - "Snow falling over multiple houses and trees on winter landscape against night sky. christmas festivity and celebration concept"
