condition: "text"
text_encoder: "t5"
clip_checkpoint: ""
t5_model_dir: "models/t5-v1_1-xxl/"

image_size: 256
num_frames: 16
model_name: "STDiT"
checkpoint: "models/OpenSora-v1-HQ-16x256x256.ckpt"
vae_checkpoint: "models/sd-vae-ft-mse.ckpt"
sd_scale_factor: 0.18215
enable_flash_attention: False
dtype: "fp32"

# sampling
sampling_steps: 100
guidance_scale: 7.0
seed: 42
ddim_sampling: False

captions:
<<<<<<< HEAD
- "The video captures the majestic beauty of a waterfall cascading down a cliff into a serene lake. The waterfall, with its powerful flow, is the central focus of the video. The surrounding landscape is lush and green, with trees and foliage adding to the natural beauty of the scene. The camera angle provides a bird's eye view of the waterfall, allowing viewers to appreciate the full height and grandeur of the waterfall. The video is a stunning representation of nature's power and beauty."
- "The video captures the majestic beauty of a waterfall cascading down a cliff into a serene lake. The waterfall, with its powerful flow, is the central focus of the video."

neg_prompts:
- ""
- ""
=======
- "A snowy forest landscape with a dirt road running through it. The road is flanked by trees covered in snow, and the ground is also covered in snow. The sun is shining, creating a bright and serene atmosphere. The road appears to be empty, and there are no people or animals visible in the video. The style of the video is a natural landscape shot, with a focus on the beauty of the snowy forest and the peacefulness of the road."
- "The video captures the majestic beauty of a waterfall cascading down a cliff into a serene lake. The waterfall, with its powerful flow, is the central focus of the video."
>>>>>>> 04a1828622592bd61c23d4de3ce69ad6a584d2b0
