# model
pretrained_model_path: "models/opensora_v1.1_stage3.ckpt"
model_max_length: 120   # TODO: 200

#enable_flash_attention: True
#use_recompute: True

# data
image_size: [512, 512]
num_frames: 16
frame_stride: 3

num_parallel_workers: 16
max_rowsize: 96

# precision
dtype: "fp16"
init_loss_scale: 65536

# training hyper-params
scheduler: "cosine_decay"
start_learning_rate: 1.e-4
end_learning_rate: 2.e-5
warmup_steps: 500   # TODO: ablate

batch_size: 1
clip_grad: True
max_grad_norm: 5.0
use_ema: False

optim: "adamw_re"
optim_eps: 1.e-8
weight_decay: 0.

epochs: 2
ckpt_save_interval: 100
