TASK_TYPE: SINGLE_TASK
read_image: True # You NEED Open It
ENABLE: true
DATASET: webvid10m
video_compositions: ['text', 'mask', 'depthmap', 'sketch', 'motion', 'image', 'local_image', 'single_sketch']
guidances: ['y', 'local_image', 'motion'] # You NEED Open It
batch_sizes: {
    "1": 1,
    "4": 1,
    "8": 1,
    "16": 1,
}
max_frames: &max_frames 16
frame_lens: [
    *max_frames,
    *max_frames,
    *max_frames,
    *max_frames,
]
vit_image_size: 224
network_name: UNetSD_temporal
resume: true
seed: 182
num_workers: 2
mvs_visual: False
chunk_size: 16
resume_checkpoint: "model_weights/non_ema_228000-7f157ec2.ckpt"
log_dir: 'outputs'

# for overfiting experiment
force_start_from_first_frame: True
misc_random_interpolation: False

