TASK_TYPE: SINGLE_TASK
ENABLE: true
DATASET: webvid10m
video_compositions: ['text', 'mask', 'depthmap', 'sketch', 'motion', 'image', 'local_image', 'single_sketch']
conditions_for_train: ["text"]  # PyTorch + Ascend setting
vit_image_size: 224
network_name: UNetSD_temporal
resume: true
seed: 182
mvs_visual: False
chunk_size: 1
#resume_checkpoint: "model_weights/non_ema_228000-7f157ec2.ckpt"
resume_checkpoint: "" # train from sracth
log_dir: 'outputs'

# accelerate or memory reduction
dataset_sink_mode: False # to show every-step loss
use_recompute: True # to avoid OOM

optim: "adamw_fp32"  # TODO: try fp32. try offload
betas: [0.9, 0.999]
optim_eps: 1.e-8
offload: False #

max_frames: 1
epochs: 2000
ckpt_save_interval: 400
ckpt_max_keep: 6

loss_scale: 65535

batch_size: 1
learning_rate: 5.e-5
warmup_steps: 100
scheduler: "constant"
end_learning_rate: 5.e-5

weight_decay: 1.e-6
use_ema: False 
