# model
space_scale: 0.5  # 0.5 for 256. 1.0 for 512
time_scale: 1.0
pretrained_model_path: "models/PixArt-XL-2-512x512.ckpt"

sd_scale_factor: 0.18215
enable_flash_attention: False

# data
image_size: 256
num_frames: 16
frame_stride: 3

# precision
dtype: "fp16"

# training hyper-params
start_learning_rate: 2.e-5
batch_size: 8
clip_grad: True

epochs: 2000
ckpt_save_interval: 200 
