generator:
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    embed_dim: 4
    monitor: val/rec_loss
    use_fp16: False  # TODO: debugging. Support bf16, fp32, fp16
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

discriminator:
  target: ldm.models.autoencoder.NLayerDiscriminator
  params:
    dtype: "fp32" # TODO: debugging

lossconfig:
  disc_start: 1  # debugging or: 50001
  kl_weight: 1.0e-06
  disc_weight: 0.5
