# system
mode: 0
use_parallel: False
num_workers: 1

# dataset
data_path: "/path/to/data"
train_batch_size: 3
gradient_accumulation_steps: 2
image_size: 512
image_filter_size: 200

# model
model_config: "configs/v1-train-cldm2.yaml"
pretrained_model_path: "/path/to/pretrained_model"
output_path: "/path/to/save/output_data"
ckpt_save_interval: 1
epochs: 80
use_ema: False
clip_grad: False
use_recompute: True

# lr scheduler
scheduler: "cosine_decay"
start_learning_rate: 2.e-5
end_learning_rate: 1.e-5
warmup_steps: 1000
decay_steps: 0

# optimizer
optim: "adamw"
betas: [0.9, 0.98]
weight_decay: 1.e-3
