# system
mode: 0
use_parallel: False
num_workers: 1

# dataset
data_path: "/path/to/data"
train_batch_size: 3
image_size: 512
image_filter_size: 200

# model
model_config: "configs/v1-train.yaml"
pretrained_model_path: "/path/to/pretrained_model"
output_path: "/path/to/save/output_data"
ckpt_save_interval: 20
epochs: 200
use_ema: False # TODO: tune
clip_grad: False # TODO: tune

# lr scheduler
scheduler: "constant"
start_learning_rate: 1e-5
end_learning_rate: 1e-5
warmup_steps: 20
decay_steps: 0

# optimizer
optim: "adamw"
betas: [0.9, 0.98]
weight_decay: 0.01
