data_path:  "/home/mindocr/yx/datasets/celeba_hq_256/train"
size: 256
crop_size: 256
flip: True

use_discriminator: False
batch_size: 4

epochs: 100
ckpt_save_interval: 1

dtype: "fp32"
init_loss_scale: 1.

scheduler: "constant"
use_ema: True
